language: node_js
node_js:
- '7'
before_script:
- npm install
script:
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: fernando.via@gmail.com
  api_key:
    secure: GUWR1XuvthX6s3DZ+vD0p6PGn/4867yTDCGIh25P5ecKVtdZKiUe8YS1Duvoo6R+PGIGqWDiSJ1MRDdsuMkVfVY3HVnypQsuzrKExOMq2YhmtBXnyR2F2Ko6cPc0cDyRTIqxoihmXsP6QrmfaUXtM8TChKpCutM4Er/CZy7XQbGzIV7mHblAI3hPe3eDVeVH5mbItciVDONEoR6wdlJYXAIYRxEcd2k5yPYZ5qEto+NwBV/SHGA65j4VzguuMy1jwA1QAgNyNNu/hfrTo2Dn4pcBBzayXnIWDL4OrG4vioC7vr89VRSkXAqJaZEg7Pd3Vbh85sbX+yssfuYZ8PggWcjriGBzVjyGvggNCK130Zt3z3fmBToUNJzeLSiu5bLtfEofQ/RYRkwwNcVw7zcbHJCF4U9i26d5b1bRgT5ayB0b4aGAW/LSV4C2J1NmcQ4OScz+mqAGhCI3BUa+fFYNdosGkrzZJdh+PnLWKe39q6mERDFi9OZReVHapBdYG7jNIzJ2B8k7mcF1ki1PGuLNUfPbaeqnQG/J1VM/FFAQ7OF5PsxfmVeUoMHrutrwt/muWg3HwzKLWA/mknqaXRGKsl8dQ5+IHfnakbPz4lxEfjS5Qv3pCUNh07oOYPMeJogersXqTkEk2LINFQsn6sEiDcq4aeO9l7nML73y6t+XaVE=
  on:
    tags: true
    repo: saguijs/create-sagui-app
